# Generated by Django 3.2.8 on 2023-02-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
